version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: Bb!123456
      POSTGRES_USER: postgres
      POSTGRES_DB: restaurant_reservation
    ports:
      - "5432:5432" 
  redis: 
    container_name: restaurant_redis
    image: 'redis'
    ports:
      - "6379:6379"
  node-app:
    # image: 'restaurant-api-docker'
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    command: ["./wait-for-it.sh", "db:5432", "--", "node", "server.js"]
